variables:
  GIT_CLEAN_FLAGS: -f -e node_modules/**
  PUBLIC_KEY: /root/.ssh/raiadkey/AzureVM02_key.pem
  PORT: 3000
  TARGET_FOLDER: /home/raiad/node/trz_pems_backend/

stages:
  - build
  # - deploy

build:
  stage: build
  script:
    - echo 'Start Building'
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 7 days
  only:
    - master
  tags:
    - IADDEV01
# deploy:
#     stage: deploy
#     script:
#         - echo 'Killing Current Process on Azure...'
#         - ssh -t -t -i $PUBLIC_KEY raiad@52.131.242.116 "cd $TARGET_FOLDER; sudo pm2 stop server.js"
#         - echo 'Deploying to the Target Server'
#         - ssh -t -t -i $PUBLIC_KEY raiad@52.131.242.116 'cd $TARGET_FOLDER; sudo find $TARGET_FOLDER* | egrep -v "ecosystem.config.js|uploads|node_modules" | xargs sudo rm -rf'
#         - rsync -aWPu -e "ssh -i $PUBLIC_KEY" dist/* raiad@52.131.242.116:$TARGET_FOLDER
#         - ssh -i $PUBLIC_KEY raiad@52.131.242.116 "cd $TARGET_FOLDER; sudo pm2 start ecosystem.config.js --env production"
#     only:
#         - master
#     tags:
#         - IADHY03

